FROM node:18-alpine3.15 AS builder
WORKDIR /app
COPY /*.json ./
COPY . .
RUN npm run build

FROM node:18-alpine3.15
WORKDIR /app
COPY --from=builder /app ./
EXPOSE 8000
CMD ["npm", "run", "start:prod"]

# //TODO: Доделать файл до нормального состояния