version: "3.9"

services:
  database:
    container_name: postgresql
    image: postgres:14.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    container_name: nest-js
    build:
      context: ../backend
    depends_on:
      - database
    restart: unless-stopped
    ports:
      - "${API_PORT}:8000"
    environment:
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}
      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_HOST=postgresql
  frontend:
    container_name: next-js
    build:
      context: ../frontend
    depends_on:
      - database
      - backend
    restart: unless-stopped
    ports:
      - "80:80"
# //TODO: Доделать файл до нормального состояния
